### ISSUE TITLE
Company.java - needs refactoring

### ISSUE THREAD

**Issue by Samurahh** [jamiehammond/sparta-simulator#41]
1. It has static fields assigned in the constructor.  ?!
2. The constructor asks for 2 parameters and ignore them.
3. ArrayList<Centre> should be different for each instance of **Company** (not static = globally available), as well as it's getter
4. LinkedList<Trainee> has the same story as (**3**)
5. Retrieving Trainee from LinkedList should be done by calling waitingList.poll() that will return the head of the queue and will remove it from the list. It will return null when the LinkedList is empty.

**Comment by Asakar** [comment]
This has been completed.
