### ISSUE TITLE
Return an ArrayList of full Centres of a specific type

### ISSUE THREAD

**Issue by Asakar** [jamiehammond/sparta-simulator#79]
DOD: The user will get the a arraylist of centres of a specific which are full. 

Testing:
1. The number of full centres of a specific type should reflect the current status. 

Difficulty: Moderate.

DEV
public ArrayList<Centre> getFullCentresByCentreType(CentreType){}

**Comment by Samurahh** [comment]
public Collection<Centre> getOpenCentresByCentreType(CentreType);
    public Collection<Centre> getClosedCentresByCentreType(CentreType);
    public Collection<Centre> getFullCentresByCentreType(CentreType);

Functionality implemented.
